name: Terraform Apply - VM

on:
  push:
    branches: ["main"]

defaults:
  run:
    working-directory: terraform/vm

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_name: ${{ secrets.ENV_PREFIX }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}
      TF_VAR_zone: ${{ secrets.GCP_ZONE }}
      tf_bucket_name: ${{ secrets.GCP_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_TF_SA_CREDS_BASE64 }}

      - name: Store SA key locally
        run: echo "${{ secrets.GCP_TF_SA_CREDS_BASE64 }}" | base64 -d > credentials.json

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.tf_bucket_name }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
